In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x = x.reshape(3,4)
x.numel()

12

In [4]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [5]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [6]:
Z = torch.zeros(3,3)

In [7]:
X = torch.ones((3,3))
Y = torch.ones((3,3))

In [8]:
X

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
Y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
id(Z)

139973285898416

In [11]:
Z = X + Y

In [12]:
id(Z)

139973655405168

In [13]:
Z[:] = X + Y

In [14]:
id(Z)

139973655405168

In [15]:
X == Y

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [16]:
X > Y

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [17]:
X < Y

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [18]:
X = torch.arange(3).reshape(3,1)

In [19]:
X

tensor([[0],
        [1],
        [2]])

In [20]:
Y = torch.arange(2).reshape(1, 2)

In [21]:
Y

tensor([[0, 1]])

In [22]:
X > Y

tensor([[False, False],
        [ True, False],
        [ True,  True]])

In [23]:
X == Y

tensor([[ True, False],
        [False,  True],
        [False, False]])

In [24]:
Q = torch.arange(9).reshape(3,3,1)

In [25]:
P = torch.arange(9).reshape(3,1,3)

In [26]:
print(Q)
print(P)

tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]],

        [[6],
         [7],
         [8]]])
tensor([[[0, 1, 2]],

        [[3, 4, 5]],

        [[6, 7, 8]]])


In [27]:
Q == P

tensor([[[ True, False, False],
         [False,  True, False],
         [False, False,  True]],

        [[ True, False, False],
         [False,  True, False],
         [False, False,  True]],

        [[ True, False, False],
         [False,  True, False],
         [False, False,  True]]])

In [28]:
import os

In [30]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每⾏表⽰⼀个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [31]:
import pandas as pd
data = pd.read_csv(data_file)

In [32]:
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [33]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2:]

In [34]:
inputs = inputs.fillna(inputs.mean())

/tmp/ipykernel_12031/64727764.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [35]:
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [36]:
inputs = pd.get_dummies(inputs, dummy_na=True)

In [37]:
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [38]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)

In [39]:
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([[127500],
         [106000],
         [178100],
         [140000]]))

In [ ]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tinyx.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price,NanMax\n') # 列名
    f.write('NA,Pave,127500,NA\n') # 每⾏表⽰⼀个数据样本
    f.write('2,NA,106000,NA\n')
    f.write('4,NA,178100,NA\n')
    f.write('NA,NA,140000,NA\n')